USE AdventureWorks2019
GO

SELECT GETDATE()
    -- , DATEADD(MINUTE, -20, GETDATE())
    , DATEADD(SECOND, 20, GETDATE())
    , DATEADD(MINUTE, 20, GETDATE())
    , DATEADD(HOUR, 20, GETDATE())
    , DATEADD(DAY, 20, GETDATE())
    , DATEADD(WEEK, 20, GETDATE())
    , DATEADD(MONTH, 20, GETDATE())
    , DATEADD(YEAR, 20, GETDATE())
