USE AdventureWorks2019
GO

SELECT DATEDIFF(YEAR, GETDATE(), DATEADD(YEAR, 20, GETDATE()))
    , DATEDIFF(DAY, GETDATE(), DATEADD(YEAR, 20, GETDATE()))
    , DATEDIFF(DAY, GETDATE(), DATEADD(YEAR, 1, GETDATE()))
    , GETDATE()
    -- , DATEADD(MINUTE, -20, GETDATE())
    , DATEADD(SECOND, 20, GETDATE())
    , DATEADD(MINUTE, 20, GETDATE())
    , DATEADD(HOUR, 20, GETDATE())
    , DATEADD(DAY, 20, GETDATE())
    , DATEADD(WEEK, 20, GETDATE())
    , DATEADD(MONTH, 20, GETDATE())
    , DATEADD(YEAR, 20, GETDATE())
